# WELCOME TO NUMPY TUTORIALS


In [1]:
print("Jello")

Jello


In [2]:
2+8*5

42

In [3]:
### This is the code that will output
print("HEllo World")
2+4+6+8

HEllo World


20

In [4]:
import numpy as np
integers=np.array([10,20,30,40,50])

In [5]:
print(integers)

[10 20 30 40 50]


In [6]:
integers[2]

30

In [7]:
integers[-3] =2


In [8]:
integers.dtype

dtype('int32')

In [9]:
integers.nbytes


20

In [10]:
integers.dtype=np.int8
integers.dtype

dtype('int8')

# MultiDimensional Arrays

In [11]:
nums=np.array([[1,2,3,4,5],[6,7,8,9,10]])
nums[0,0]

1

In [12]:
nums.size

10

In [13]:
nums.ndim

2

In [14]:
nums.shape # Row, Column

(2, 5)

In [15]:
multi=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(multi)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [16]:
multi.shape

(2, 2, 3)

In [17]:
multi[0,0,2] # INdexing in tensor first is for slecting which array then row then column

3

# Creating arrays from Lists and other Python structures

In [18]:
first_list=[1,2,3,4,5,6,7,8,9]

In [19]:
first_array =np.array(first_list)

In [20]:
first_array


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
second_list=[1,2.3,5.6,8,9]

In [22]:
sec_array=np.array(second_list)

In [23]:
sec_array

array([1. , 2.3, 5.6, 8. , 9. ])

In [24]:
sec_array.dtype


dtype('float64')

In [25]:
third_list=["Hello",1,2,3]

In [26]:
third_array=np.array(third_list)

In [27]:
third_array

array(['Hello', '1', '2', '3'], dtype='<U11')

In [28]:
first_tuple=(1,2,3)

In [29]:
arr=np.array(first_tuple)

In [30]:
arr.dtype


dtype('int32')

# Intrinsic NumPy Array Creation

In [31]:
#numpy.arrange

In [32]:
# numpy.arrange([start,] stop, [step,] dtype=None,*,like=None) # SYntax 

In [33]:
intarr=np.arange(10)

In [34]:
intarr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
intarr_1=np.arange(1,10)

In [36]:
intarr_1 # Till last element -1 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
intarr_2=np.arange(1,10,0.5)

In [38]:
intarr_2

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [39]:
# numpy.linspace for float

In [40]:
first_float=np.linspace(10,20,)

In [41]:
first_float

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [42]:
# Third argument in linspace is the number odf elem,ents you eant in the range

In [43]:
sec_flo=np.linspace(1,10,5)

In [44]:
sec_flo

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [45]:
# np.random.rand

In [46]:
fiurst_ran=np.random.rand(10)

In [47]:
fiurst_ran


array([0.47140848, 0.43427976, 0.03101476, 0.82809686, 0.23371495,
       0.02268512, 0.49793838, 0.42773065, 0.80440925, 0.13439739])

In [48]:
# numpy.random.randint

In [49]:
third_arr=np.random.randint(0,100,20)
third_arr

array([10, 86, 54, 70, 30, 65, 91, 51, 13, 69, 65, 43,  3, 93, 32, 22, 94,
       13, 84, 62])

# Creating arrays filled with constant Values

In [50]:
# np.zeros()

In [51]:


first_z=np.zeros(5)
first_z

array([0., 0., 0., 0., 0.])

In [52]:
sec_z=np.zeros((4,5))
sec_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
#np.ones()

In [54]:
first_one=np.ones(3)
first_one

array([1., 1., 1.])

In [55]:
sec_one=np.ones((3,4))
sec_one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
#fill 
#only one dimensional arrays
# first create empty array then fill with similar values

In [57]:
#np.empty

In [58]:
first_fill= np.empty(10,dtype=int)
first_fill.fill(12)
first_fill

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [59]:
#full
# 1 or 2 dimensional arrays
#np.full((dimension),constant)

In [60]:
first_full=np.full(5,10)
first_full

array([10, 10, 10, 10, 10])

In [61]:
sec_full=np.full((3,3),4)
sec_full

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

# Finding shape and size

In [62]:
#dtype
#shape give dimensions
#ndim gives one,two three kind of dimension (like array is 3 dimensional)
# size gives number of elements

In [63]:
first_arr=np.arange(20)
first_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
sec_arr=np.linspace((1,2),(10,20),10)
sec_arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [65]:
third_arr=np.full((2,2,2),10)
third_arr

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [66]:
np.shape(third_arr) # or third_arr.shape

(2, 2, 2)

In [67]:
np.shape(first_arr)


(20,)

In [68]:
sec_arr.size

20

In [69]:
arr=np.array([1,2,3,4,5])
arr[0]=2.5
print(arr)

[2 2 3 4 5]


In [70]:
arre=np.random.rand(0,4,3)
print(arre)

[]


In [71]:
array1=['Wa',24,'CA']
array2=np.array(array1)
array2

array(['Wa', '24', 'CA'], dtype='<U11')

In [72]:
from numpy import shape

# Adding,removing and sorting elements

In [73]:
#insert at desired index
#append at last element

In [74]:
first_arr=np.array([1,2,3,4])
new_arr=np.insert(first_arr,3,4)
new_arr

array([1, 2, 3, 4, 4])

In [75]:
new2_arr=np.append(first_arr,3)
new2_arr

array([1, 2, 3, 4, 3])

In [76]:
#Deleting element from array

In [77]:
new3_arr=np.delete(new_arr,4)
new3_arr

array([1, 2, 3, 4])

In [78]:
#sorting

In [79]:
print(np.sort(np.random.rand(10)))

[0.03004974 0.16555203 0.24340036 0.27137453 0.35480427 0.3851938
 0.48974163 0.55434854 0.59416878 0.85850601]


In [80]:
np.random.rand(10)

array([0.08482641, 0.52435573, 0.17558219, 0.56915675, 0.14537456,
       0.79271805, 0.21368793, 0.57921846, 0.84779219, 0.03757622])

In [81]:
print(np.flip((np.sort(np.random.rand(10),))))

[0.97889138 0.92298492 0.9100489  0.83403263 0.70192081 0.54780435
 0.38491155 0.31574709 0.20943876 0.0409163 ]


In [82]:
#np.flip() negataion of order


# Copies and Views

In [83]:
# Any change made in original array will not be  be reflected in copied array
# But the new is assigned from old one then changes will effect both equally

In [84]:
#.copy()

In [85]:
zz_arr=new_arr.copy()
zz_arr

array([1, 2, 3, 4, 4])

In [86]:
zz_arr == new_arr

array([ True,  True,  True,  True,  True])

In [87]:
#view()
# Works both ways changes made in any one will be reflected on both

In [88]:
z_arr=new_arr.view()
z_arr

array([1, 2, 3, 4, 4])

In [89]:
z_arr[1]=200

In [90]:
print(z_arr)
print(new_arr)

[  1 200   3   4   4]
[  1 200   3   4   4]


# Reshaping Arrays

In [91]:
# Number of elemnts remain same while shape changes

In [92]:
#np.rehape()

In [93]:
first=np.arange(1,13)
first

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [94]:
sec=np.reshape(first,(4,3))
sec

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [95]:
# Give new shape input such a way that totaal number of elemnts remain same


In [96]:
# rehaping to 3 dimensional array

In [97]:
third=np.reshape(first,(3,2,2))
third

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [98]:
four=np.reshape(third,12)
four  # This process is known as flattening

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
# numpy.ndarray.flatten
# Return a copy of the array collapsed into one dimension

In [100]:
# numpy.ravel
# Return a contiguous flattened array
#memory efficient as it does not create copy 
# IT creates view

In [101]:
fifth=third.flatten()
fifth

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [102]:
sixth=third.ravel()
sixth

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Indexing and Slicing

In [103]:
# array[1:4] element at index one to element at index 3 (last-1) slicing


In [104]:
ff=np.reshape(np.arange(12),(3,4))
ff

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
ff[1,1]

5

In [106]:
ff[1]

array([4, 5, 6, 7])

In [107]:
ff=np.reshape(np.arange(12),(3,2,2))
ff

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [108]:
ff[2,0,0]

8

In [109]:
ff[1,1,1]

7

In [110]:
#In multi dimensional array while indexing [i,j,k] i refers to array to which we are refering j,k refers to element of that array

In [111]:
# neagtive indexing


In [112]:
ff[-1,-1,-1]

11

In [113]:
#slicing

In [114]:
ff[-1,0:2,0:2]

array([[ 8,  9],
       [10, 11]])

In [115]:
first[-3:] # will give last three elemnts

array([10, 11, 12])

In [116]:
# every other element
# emit start,stop will enter only step

In [117]:
ff[::2]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]]])

In [118]:
first[::2]

array([ 1,  3,  5,  7,  9, 11])

# Joining and splitting arrays

In [119]:
#Functions for joining
"""
concatenate
stack
hstack
vstack
"""

'\nconcatenate\nstack\nhstack\nvstack\n'

In [120]:
# consider dimensional requirement for joining

In [121]:
# ALso how we decide it will be joined row wise or column wise
# For row wise joining number of rows must be equal silmilarly for cloumn wise joining
# column wise joining will be downside and row wise joining will be right side

In [122]:
first_a=np.arange(1,11)
sec_ar=np.arange(11,21)
print(first_a)
print(sec_ar)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [123]:
third_ar=np.concatenate((first_a,sec_ar))
print(third_ar)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [124]:
third_2r=np.array([[1,2,3],[4,5,6]])
third_3r=np.array([[7,8,0],[10,11,12]])
fou_ar=np.concatenate((third_2r,third_3r),axis=1)
fou_ar

array([[ 1,  2,  3,  7,  8,  0],
       [ 4,  5,  6, 10, 11, 12]])

In [125]:
# stack is done along new axis


In [126]:
st_arr=np.stack((first_a,sec_ar))
st_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [127]:
# horizontal stacking hstack
# vertical stacking v stack

In [128]:
hst_arr=np.hstack((first_arr,sec_ar))
hst_arr

array([ 1,  2,  3,  4, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [129]:
vst_arr=np.vstack((first_a,sec_ar))
vst_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [130]:
# splitiing
"""
split
array_split
hsplit
vsplit
"""

'\nsplit\narray_split\nhsplit\nvsplit\n'

In [131]:
# It only splits when total number of elemnts are divisible by number of splits

In [132]:
jj=np.split(vst_arr,2)
jj
print(jj[1])

[[11 12 13 14 15 16 17 18 19 20]]


In [133]:
# when the above condition is satisfied use array)_split it will adjust automatically

In [134]:
j=np.array_split(vst_arr,8)
j

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]),
 array([], shape=(0, 10), dtype=int32),
 array([], shape=(0, 10), dtype=int32),
 array([], shape=(0, 10), dtype=int32),
 array([], shape=(0, 10), dtype=int32),
 array([], shape=(0, 10), dtype=int32),
 array([], shape=(0, 10), dtype=int32)]

In [135]:
xx=np.vsplit(vst_arr,2)
xx

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])]

# Arithmetic OPerations and Functions

In [136]:
# VEctorization:_ OPeration can be executed in parallel on multiple elemnts of the array

In [137]:
#Benefits:-
# Higher performing code
# Less verbose code
# Better maintainability

In [138]:
""" 
Will cover following Operations
Addition
Subtraction
Multiplication
Division
Exponentiation
Specific functions to perform them
"""

' \nWill cover following Operations\nAddition\nSubtraction\nMultiplication\nDivision\nExponentiation\nSpecific functions to perform them\n'

In [139]:
a=np.arange(1,11)
b=np.arange(11,21)
a+b

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [140]:
a-b

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [141]:
a*b


array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [142]:
# * is known as asterisk

In [143]:
b/a

array([11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ,
        2.66666667,  2.42857143,  2.25      ,  2.11111111,  2.        ])

In [144]:
b%a


array([0, 0, 1, 2, 0, 4, 3, 2, 1, 0])

In [145]:
a**b # a power b

array([          1,        4096,     1594323,   268435456,   452807053,
        -683606016, -2094633337,           0,  -400556711,  1661992960])

In [146]:
a*20

array([ 20,  40,  60,  80, 100, 120, 140, 160, 180, 200])

In [147]:
np.add(a,b)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [148]:
np.subtract(b,a)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [149]:
np.multiply(a,b)

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [150]:
np.divide(b,a)

array([11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ,
        2.66666667,  2.42857143,  2.25      ,  2.11111111,  2.        ])

In [151]:
np.power(b,a)

array([         11,         144,        2197,       38416,      759375,
          16777216,   410338673, -1864941312,   565150579,   797966336])

In [152]:
 np.mod(b,a)  # %

array([0, 0, 1, 2, 0, 4, 3, 2, 1, 0])

In [153]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

# Broadcasting

In [154]:
# When we need to apply arithmetic operations to arrays of different dimensions,
#broadcasting helps to acheive that

In [155]:
# Subject to certain constraints, the smaller array is broadcast across the 
#larger array so that they have compatible shapes

In [156]:
ab=np.reshape(np.arange(1,10),(3,3))
bb=np.arange(1,4)
print(ab)
print(bb)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [157]:
ab+bb ## bb is broadcasted to match dimensions of ab bb is copied two times then elemntwise addition

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [158]:
cc=np.arange(1,3)
ab+cc # Atleast have same number of elemnts in row meaning atleast one dimension must be same

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [ ]:
d=np.arange(24).reshape(2,3,4)
e=np.arange(4)
d+e

In [ ]:
# Aggregate functions
#takes array as input and returns scalar as output
# These are statistics such as averages,standard deviation,function 
#for calculating sum and multiplication developments in array

In [ ]:
print(d.sum())

In [ ]:
#axis=0 means row
#axis =1 means columns
print(d.sum(axis=0))
print(d.sum(axis=1))

In [ ]:
d.prod()

In [ ]:
np.average(d)

In [ ]:
np.mean(d)

np.min(d)

In [ ]:
np.std(d)

# How to get unique items and counts

In [ ]:
np.unique(d)

In [ ]:
np.unique(d,axis=0)

In [ ]:
# Getting indices of unique elemnts


In [ ]:
np.unique(d,return_index=True)

In [ ]:

# First array contains unique elements
#Second array contains index of unique elemnts

In [ ]:
# calculating frequency of unique elemnts

In [ ]:
np.unique(d,return_counts=True)

# TRanspose like operations, moveaxis, swap axis

In [ ]:
np.transpose(d)

In [ ]:
np.transpose(e,axes=0)

In [ ]:
dfd=np.reshape(np.arange(12),(3,4))
np.transpose(dfd)

In [ ]:
# numpy.moveaxis(a,source,destination)
# a array whose axes should be reordered
# source: original position of the axes to move, These must be unique
# destination : Destination positions for each of the original axes, These must be unique

In [ ]:
np.moveaxis(d,0,-1)

In [ ]:
np.swapaxes(d,0,2)

# Reversing an array

In [ ]:
a[::-1] # using indexing

In [ ]:
#using flip function

In [ ]:
np.flip(a)

In [ ]:
np.flip(dfd,1)

# Universal Functions

In [ ]:
numbers=np.arange(1,11)
numbers

In [ ]:
np.sin(numbers)

In [ ]:
np.log(numbers)

In [ ]:
integers=np.arange(1,101)

def modulo(val):
    return (val%10)
mod_10=np.frompyfunc(modulo,1,1)

mod_integers=mod_10(integers)
print("mod integers",mod_integers)

# Strides

In [ ]:
numbers=np.arange(10,dtype=np.int8)
numbers

In [ ]:
numbers.strides

In [ ]:
numbers=numbers.reshape(2,5)
numbers

In [ ]:
numbers.strides

In [ ]:
# need to jump 5 bytes to get to next row
# need to jump 1 byte to get to next column

In [ ]:
first_array=np.zeros((100000,))
first_array

In [ ]:
second_array=np.zeros((100000*100,))[::100]
second_array

In [ ]:
first_array.shape

In [ ]:
first_array.size

In [ ]:
second_array.shape

In [ ]:
first_array.strides

In [ ]:
second_array.strides

In [ ]:
%timeit first_array.sum()

In [ ]:
%timeit second_array.sum()

# Dates and Time

In [ ]:
# Time Series Analysis

In [ ]:
np.datetime64('2024-08-14')

In [ ]:
np.datetime64('2024-08')

In [ ]:
# counting weekdays using busday

In [ ]:
print('Number of weekdays in 2023:')
print(np.busday_count('2023','2024'))

In [ ]:
print('Number of weekdays in 2023:')
print(np.busday_count('2023-06','2023-07'))

In [ ]:
# checking valid business day

In [ ]:
np.is_busday(np.datetime64('2024-06-05'))

# Linear Algebra Capabilities

In [ ]:
firs=np.arange(16).reshape(4,4)

In [ ]:
first_matrix=np.matrix(firs)
first_matrix

In [ ]:
sec_matrix=np.matrix(np.identity(4))
sec_matrix

In [ ]:
# matmul for matrix multiplication

In [ ]:
#Finding Inverse

In [ ]:
ff=np.array([[3,4] ,[5,6]])
thir_matrix=np.matrix(ff)
inverse=np.linalg.inv(thir_matrix)
inverse

In [ ]:
inverse*thir_matrix

In [ ]:
# solve using 
#np.linalg.solve(A,b)

# Matrix Decomposition

In [ ]:
# Lower-upper decomposition (LU)
# Singular Value Decomposition (SVD)
# QR decomposition 
# Cholesky factorization

In [ ]:
#eigen values and eigen vector

In [ ]:
girst_matrix=np.matrix([[4,8],[10,14]])
print(girst_matrix)

In [ ]:
eigenvalues,eigenvectors=np.linalg.eig(girst_matrix)
print(eigenvalues)
print(eigenvectors)

In [ ]:
eigenvalues=np.linalg.eigvals(girst_matrix)
print(eigenvalues)

In [ ]:
A=np.mat("3 1 4; 1 5 9;2 6 5")
print(A)
U, Sigma, V =np.linalg.svd(A,full_matrices=False)
print(U)
print("SIgma:",Sigma)
print(V)

In [ ]:
# checking decomposition 's correctness

In [ ]:
print(U*np.diag(Sigma)*V)

In [ ]:
# QR DEcomposition
#M=Q*R
# R is upper Triangular
# Q is orthogonal Matrix

In [ ]:
b=np.array([1,2,3]).reshape(3,1)
q,r =np.linalg.qr(A)
x=np.dot(np.linalg.inv(r),np.dot(q.T,b))
x

# Ploynomial Many-Terms

In [ ]:
from numpy.polynomial import Polynomial

In [ ]:
first_polynomial=np.polynomial.Polynomial([2,-3,1])
first_polynomial

In [ ]:
second_ploynomial=np.polynomial.Polynomial.fromroots([1,2])

second_ploynomial

In [ ]:
# Finding roots


In [ ]:
first_polynomial.roots()

In [ ]:
second_ploynomial.roots()

In [ ]:
integral=second_ploynomial.integ()
integral

In [ ]:
integral.deriv()

# Linear Regression

In [ ]:
# Used in Supervised machine learning 